
TVEC_ITEM_TYPE textequ <REAL8>
TSortedVectorName textequ <Real8VectorS>
TSortedVectorID = 30101
TVectorDupCheck = FALSE 
TVectorOrdering textequ <TSV_ASCENDING>
AncestorVectorName textequ <Real8Vector>
% include &ObjPath&TSortedVector.inc

TVEC_ITEM_TYPE textequ <DWORD>
TSortedVectorName textequ <DwordVectorS>
TSortedVectorID = 30102
TVectorDupCheck = FALSE 
TVectorOrdering textequ <TSV_DESCENDING>
AncestorVectorName textequ <DWordVector>
% include &ObjPath&TSortedVector.inc
